name: Java CI - Polling tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    name: JDK ${{matrix.java-version}} JVM build and tests for polling profile
    timeout-minutes: 120
    strategy:
      fail-fast: false
      matrix:
        java-version: [21]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      name: checkout

    - uses: actions/setup-java@v1
      name: Set up JDK ${{ matrix.java-version }}
      with:
        distribution: "temurin"
        java-version: ${{ matrix.java-version }}

    - name: Build with Maven
      run: mvn clean test -Dquarkus.test.profile=test,polling
